default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: repo
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default
  database: repo_development

test:
  <<: *default
  database: repo_test

production:
  <<: *default
  database: 
